- name: Write nxos bridge interface configuration files
  become: true
  ansible.builtin.template:
    src: templates/nxos_bridge.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/nx{{ '%03d' % item }}.nmconnection
    mode: 0600
    owner: root
    group: root
  loop: "{{ range(1, 9)|list }}"
  register: nxos_bridges
- name: Reload NetworkManager.service
  when:
    - nxos_bridges.changed
  become: true
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: true
    state: restarted
