network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      dhcp4: no
    enp3s0:
     dhcp4: no
     addresses: [192.168.29.1/24]
  bridges:
    br-dataplane:
      openvswitch: {}
      interfaces:
      - enp2s0
    br-ex:
      openvswitch: {}
      dhcp4: no
      addresses: [172.24.5.1/24]
