---
- name: Create stack user for devstack
  become: true
  ansible.builtin.user:
    create_home: true
    generate_ssh_key: true
    name: stack
    home: /opt/stack
    shell: /bin/bash
    ssh_key_bits: 4096
    state: present
- name: Set up sudo for stack user
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'stack ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
