---
- name: Install Virtual BMC
  become: true
  ansible.builtin.pip:
    name: virtualbmc
    virtualenv: /opt/vbmc
    virtualenv_command: python3 -m venv
    virtualenv_site_packages: true
- name: Write Virtual BMV systemd unit
  become: true
  ansible.builtin.copy:
    src: vbmcd.service
    dest: /etc/systemd/system/vbmcd.service
    owner: root
    group: root
- name: Enable and start Virtual BMC (vbmcd.service)
  become: true
  ansible.builtin.systemd:
    name: vbmcd.service
    daemon_reload: true
    enabled: true
    state: started
